# Generated by Django 4.2.15 on 2024-09-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
        ('accounts', '0003_remove_user_test'),
    ]

    operations = [
    ]
