# Generated by Django 5.1 on 2024-09-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='UID',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
