# Generated by Django 5.1 on 2024-09-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_manager', '0003_remove_trip_id_alter_trip_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='UID',
            field=models.PositiveIntegerField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
