# Generated by Django 5.1 on 2024-09-20 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_manager', '0004_event_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='trip',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='trip_manager.trip'),
            preserve_default=False,
        ),
    ]
