# Generated by Django 5.1 on 2024-09-21 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_manager', '0005_remove_event_uid_remove_trip_events_event_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trip_manager.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='UID',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
