# Generated by Django 4.2.15 on 2025-09-06 08:48

import apps.daytrips.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daytrip',
            fields=[
                ('title', models.CharField(max_length=32)),
                ('desc', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('code', models.CharField(default=apps.daytrips.models.generate_unique_code, max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('daytrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='daytrips.daytrip')),
            ],
        ),
    ]
