# Generated by Django 4.2.15 on 2025-09-10 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daytrips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_going', models.BooleanField(default=False)),
                ('is_driver', models.BooleanField(default=False)),
                ('daytrip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='daytrips.daytrip')),
            ],
        ),
    ]
