# Generated by Django 4.2.15 on 2026-07-06 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daytrips', '0002_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='daytrip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='daytrips.daytrip'),
        ),
    ]
