# Generated by Django 5.0.7 on 2024-08-04 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=250)),
                ('home_address', models.CharField(max_length=250)),
                ('isDriver', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='passenger_cluster.person')),
            ],
            bases=('passenger_cluster.person',),
        ),
    ]
