# Generated by Django 4.2.15 on 2024-08-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_cluster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lname',
        ),
    ]
