# Generated by Django 4.2.15 on 2024-08-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_cluster', '0002_remove_person_fname_remove_person_home_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fname',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='home_address',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='lname',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
